name    'brucem-kibana3'
version '0.0.1'
source 'git://github.com/brucem/puppet-kibana3.git'
author 'brucem'
license 'Apache License, Version 2.0'
summary 'Kibana3'
description 'Install Kibana3 and configure a nginx server'
project_page 'http://github.com/brucem/puppet-kibana3'

dependency 'dhutty/nginx'
dependency 'puppetlabs/vcsrepo'
dependency 'puppetlabs/git'
